server:
  port: 10010

spring:
  application:
    name: leyou-gateway
  servlet:
    multipart:
      max-file-size: 10MB #限制文件上传最大大小
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5 #每个五秒发送心跳

zuul:
  prefix: /api  #路由前缀 访问路径前的
  routes:
    item-service: /item/**
    upload-service: /upload/**
