server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  application:
    name: item-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  #服务的提供者每间隔5s给注册中心发送心跳
